apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello
subjects:
- kind: ServiceAccount
  name: hello
roleRef:
  kind: Role
  name: hello
  apiGroup: rbac.authorization.k8s.io