apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hello
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
    - pods
    - services
    - statefulsets.apps
    - persistentvolumeclaims
    - persistentvolumes
    - replicasets
    - deployments
  verbs: ["*"]